<a href="https://colab.research.google.com/github/gutivanian/API_Ecommerce_Midtrans/blob/master/agents/gemini_data_analytics/intro_gemini_data_analytics_http.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Intro to Gemini Data Analytics

| Author |
| --- |
| [Aditya Verma](https://github.com/vermaAstra) |

# Background and Overview
The **Conversational Analytics API** lets you chat with your BigQuery or Looker data anywhere, including embedded Looker dashboards, Slack and other chat apps, or even your own web applications. Your team members can get answers where they need them, when they need them, in the applications they use every day. You can find the [Colab example with the Python SDK here](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/agents/gemini_data_analytics/intro_gemini_data_analytics_sdk.ipynb). This is a **Pre-GA** product. See [documentation](https://cloud.google.com/gemini/docs/conversational-analytics-api/overview) for more details.

Please provide feedback to conversational-analytics-api-feedback@google.com
<br>
### This notebook will help you
1. Authenticate to Google Cloud
2. Add data
3. Perform agent operations (create, list, get, delete)
4. Manage conversations (create, list, get, delete)
5. Ask questions with your agent

# Get Started

## API Enablement

**Please fill in the billing_project form field with your own Google Cloud project.  The project must have the following APIs enabled:**
-  [cloudaicompanion API](https://console.cloud.google.com/apis/library/cloudaicompanion.googleapis.com)
-  [Gemini Data Analytics API](https://console.cloud.google.com/apis/library/geminidataanalytics.googleapis.com)
-  [BQ API](https://console.cloud.google.com/marketplace/product/google/bigquery.googleapis.com)
-  [Dataform API](https://console.cloud.google.com/apis/library/dataform.googleapis.com)
- [Agent Platform API](https://console.cloud.google.com/apis/library/aiplatform.googleapis.com)

You may pass in any BigQuery project/dataset/table for which you have read permissions.

## Auth and Imports

In [30]:
import json
import json as json_lib
import textwrap

import altair as alt
from google.colab import auth
from IPython.display import HTML, display
import pandas as pd
from pygments import formatters, highlight, lexers
import requests

auth.authenticate_user()

access_token = !gcloud auth application-default print-access-token
headers = {
    "Authorization": f"Bearer {access_token[0]}",
    "Content-Type": "application/json",
}

# Datasource and Billing project


*   Define your billing project within Google Cloud
*   Link your agent to data sources (BigQuery, Looker, Looker Studio)

In [31]:
# @title Billing Project and Prompt (System Instruction)

# fmt: off
billing_project = "project-4edfdecd-6192-4f0d-be4"  # @param {type:"string"}

location = "global"
api_version = "v1beta"

# provide critical context for your Conversational Analytics Agent here
system_instruction = "Think like an Analyst"  # @param {type:"string"}
# fmt: on

bigquery_data_sources = {}
looker_data_sources = {}
looker_studio_data_sources = {}

In [32]:
# @title BigQuery Datasource

bigquery_data_sources = {
    "bq": {
        "tableReferences": [
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "distribution_centers",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "events",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "inventory_items",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "order_items",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "orders",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "products",
            },
            {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "ecommerce",
                "tableId": "users",
            },
            # Add more table references here
        ]
    }
}

# optional example queries (only leveraged for BigQuery datasources currently)
# Example queries can be parameterized in which case parameters must be defined.
# Each parameter requires a name (exactly as it appears in the question and SQL),
# description, and a valid dataType
# (https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/data-types#data_type_list).
example_queries = [
    {
        "naturalLanguageQuestion": (
            "What is the total sales revenue generated by each product category?"
        ),
        "sqlQuery": "SELECT t2.product_category, SUM(t1.sale_price) AS total_revenue FROM `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS t1 JOIN `project-4edfdecd-6192-4f0d-be4.ecommerce.inventory_items` AS t2 ON t1.inventory_item_id = t2.id GROUP BY t2.product_category ORDER BY total_revenue DESC;",
    },
]

glossary_terms = [
    {
        "display_name": "revenue",
        "description": ("total sales"        ),
        "labels": ["rev"],
    },
]

use_glossary_terms = True  # @param {type: "boolean"}
use_example_queries = True  # @param {type:"boolean"}

In [38]:
# @title Select datasource

selected_datasource = "bigquery_data_sources"  # @param ["bigquery_data_sources", "looker_data_sources", "looker_studio_data_sources"]

datasource_map = {
    "bigquery_data_sources": bigquery_data_sources,
}

datasource_references = datasource_map[selected_datasource]

bq_selected = False

if selected_datasource == "looker_data_sources":
  looker_selected = True
elif selected_datasource == "bigquery_data_sources":
  bq_selected = True
elif selected_datasource == "looker_studio_data_sources":
  looker_studio_selected = True

# Environment

In [39]:
# fmt: off
environment = "prod"  # @param ["prod", "staging", "autopush"]
# fmt: on

base_url = "https://geminidataanalytics.googleapis.com"

if environment == "autopush":
  base_url = "https://autopush-geminidataanalytics.sandbox.googleapis.com"
elif environment == "staging":
  base_url = "https://staging-geminidataanalytics.sandbox.googleapis.com"
else:
  base_url = "https://geminidataanalytics.googleapis.com"

# Data Agent Services

In [40]:
# @title Create Data Agent

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents"

data_agent_payload = {
    "name": (
        f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
    ),  # Optional
    "description": "This is the description of data_agent.",  # Optional
    "data_analytics_agent": {
        "published_context": {
            "datasource_references": datasource_references,
            "system_instruction": system_instruction,
            "options": {
                "analysis": {
                    # Optional - if wanting to use advanced analysis with python.
                    # Default is False.
                    "python": {"enabled": False}
                }
            },
        }
    },
}

if bq_selected:
  if use_example_queries:
    data_agent_payload["data_analytics_agent"]["published_context"][
        "example_queries"
    ] = example_queries
  if use_glossary_terms:
    data_agent_payload["data_analytics_agent"]["published_context"][
        "glossary_terms"
    ] = glossary_terms
elif looker_selected and use_looker_golden_queries:
  data_agent_payload["data_analytics_agent"]["published_context"][
      "looker_golden_queries"
  ] = looker_golden_queries

params = {"data_agent_id": data_agent_id}  # Optional

data_agent_response = requests.post(
    data_agent_url, params=params, json=data_agent_payload, headers=headers
)

if data_agent_response.status_code == 200:
  print("Data Agent created successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error creating Data Agent: {data_agent_response.status_code}")
  print(data_agent_response.text)

Error creating Data Agent: 409
{
  "error": {
    "code": 409,
    "message": "Resource 'projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd' already exists",
    "status": "ALREADY_EXISTS",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ResourceInfo",
        "resourceName": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
      }
    ]
  }
}

In [41]:
# @title Get Data Agent

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"

data_agent_response = requests.get(data_agent_url, headers=headers)

if data_agent_response.status_code == 200:
  print("Fetched Data Agent successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error: {data_agent_response.status_code}")
  print(data_agent_response.text)

Fetched Data Agent successfully!
{
  "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd",
  "displayName": "test ecommerce",
  "description": "This is the latest description of data_agent.",
  "labels": {
    "published_context": "bq"
  },
  "createTime": "2026-05-26T07:57:47.474954690Z",
  "updateTime": "2026-05-26T08:25:49.745038889Z",
  "dataAnalyticsAgent": {
    "publishedContext": {
      "systemInstruction": "Think like an Analyst",
      "datasourceReferences": {
        "bq": {
          "tableReferences": [
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "distribution_centers"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "events"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "inventory_items"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "order_items"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "orders"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "products"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "users"
            }
          ]
        }
      }
    },
    "lastPublishedContext": {
      "options": {
        "datasource": {},
        "model": "MODEL_UNSPECIFIED"
      },
      "exampleQueries": [
        {
          "naturalLanguageQuestion": "What is the total sales revenue generated by each product category?",
          "sqlQuery": "SELECT\n    t2.product_category,\n    SUM(t1.sale_price) AS total_revenue\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS t1\nJOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.inventory_items` AS t2\nON\n    t1.inventory_item_id = t2.id\nGROUP BY\n    t2.product_category\nORDER BY\n    total_revenue DESC;"
        },
        {
          "naturalLanguageQuestion": "Which are the top 5 users based on their total spending across all orders, including their full name?",
          "sqlQuery": "SELECT\n    t1.first_name,\n    t1.last_name,\n    SUM(t2.sale_price) AS total_spent\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.users` AS t1\nJOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS t2\nON\n    t1.id = t2.user_id\nGROUP BY\n    t1.first_name,\n    t1.last_name\nORDER BY\n    total_spent DESC\nLIMIT 5;"
        },
        {
          "naturalLanguageQuestion": "Which product brands have sold the highest total number of individual inventory items?",
          "sqlQuery": "SELECT\n    t2.product_brand,\n    COUNT(t1.id) AS total_items_sold\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS t1\nJOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.inventory_items` AS t2\nON\n    t1.inventory_item_id = t2.id\nGROUP BY\n    t2.product_brand\nORDER BY\n    total_items_sold DESC\nLIMIT 10;"
        },
        {
          "naturalLanguageQuestion": "What is the approximate median age and the 25th and 75th percentile ages for users who have performed a 'page_view' event?",
          "sqlQuery": "SELECT\n    APPROX_QUANTILES(t1.age, 100)[OFFSET(25)] AS p25_age,\n    APPROX_QUANTILES(t1.age, 100)[OFFSET(50)] AS median_age,\n    APPROX_QUANTILES(t1.age, 100)[OFFSET(75)] AS p75_age\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.users` AS t1\nJOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.events` AS t2\nON\n    t1.id = t2.user_id\nWHERE\n    t2.event_type = 'page_view' AND t1.age IS NOT NULL;"
        }
      ],
      "datasourceReferences": {
        "bq": {
          "tableReferences": [
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "distribution_centers"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "events"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "inventory_items"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "order_items"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "orders"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "products"
            },
            {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "datasetId": "ecommerce",
              "tableId": "users"
            }
          ]
        }
      },
      "userFunctions": {}
    }
  }
}

In [ ]:
# @title List Data Agents

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents"

data_agent_response = requests.get(data_agent_url, headers=headers)

if data_agent_response.status_code == 200:
  print("Data Agents Listed successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error Listing Data Agents: {data_agent_response.status_code}")
  print(data_agent_response.text)

In [11]:
# @title List Accessible Data Agents

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents:listAccessible"

# Choose the desired creator filter
# fmt: off
creator_filter = "NONE"  # @param ["NONE", "CREATOR_ONLY", "NOT_CREATOR_ONLY"]
# fmt: on

# Add the creator_filter as a query parameter
params = {"creator_filter": creator_filter}

data_agent_response = requests.get(
    data_agent_url, headers=headers, params=params
)

if data_agent_response.status_code == 200:
  print("Data Agents Listed successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error Listing Data Agents: {data_agent_response.status_code}")
  print(data_agent_response.text)

Data Agents Listed successfully!
{
  "dataAgents": [
    {
      "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_ac33f6bf-d236-4079-96a3-a515f3f9fd49",
      "displayName": "TPC-DS Retail Insights",
      "description": "Expert retail analyst for the TPC-DS 1G dataset.\n\nExample questions: (1) Find customers who have returned items more than 20% more often than the average customer returns for a store in TN for the year 2000.\n(2) Report the total extended sales price per item brand of manufacturer 128 for all sales in November (month 11).\n(3) List all the states with at least 10 customers who during January 2001 bought items with the price tag at least 20% higher than the average price of items in the same category.",
      "labels": {
        "readonly": "true",
        "sample-agent-signature": "sample_agent_tpc_ds_v1"
      },
      "createTime": "2026-05-26T07:53:50.690425803Z",
      "updateTime": "2026-05-26T07:53:51.376230511Z",
      "dataAnalyticsAgent": {
        "stagingContext": {
          "systemInstruction": "**Synonyms**\n* Customer: client, user, buyer\n* Revenue: sales, sales value, ss_ext_sales_price\n* Refunds: returns, sr_return_amt\n* Product: item\n* Address: customer location, customer address, home state\n\n**Key fields**\n* Identifiers: c_customer_id (Customer ID), i_item_id (Product ID), s_store_id (Store ID), ca_address_id (Address ID)\n* Timestamps: d_date (Date)\n* Metrics: ss_ext_sales_price (Total Revenue), ss_net_profit (Profit), sr_return_amt (Return Amount), i_current_price (Current Price)\n\n**Excluded Fields**\n* Surrogate Keys: Avoid using any fields ending in _sk (e.g., c_customer_sk, ss_item_sk, d_date_sk, ca_address_sk) in final text answers or displays.\n* Technical Metadata: ss_sold_time_sk, sr_return_time_sk, d_date_id.\n\n**Filtering and grouping**\n* Time: Use d_year for year-based filtering and d_moy for monthly grouping from the date_dim table.\n* Geography: Use s_state and s_store_name for store-based analysis; use ca_state, ca_city, and ca_county for customer home-location analysis.\n* Attributes: Use i_category and i_brand for product-level analysis.\n\n**Join relationships**\n* Sales & Returns: Link store_sales and store_returns by joining on both ss_item_sk = sr_item_sk and ss_ticket_number = sr_ticket_number.\n* Fact to Dimension: Combine fact tables (store_sales, store_returns) with dimension tables using surrogate keys:\n    * Join to date_dim on ss_sold_date_sk = d_date_sk or sr_returned_date_sk = d_date_sk\n    * Join to customer on ss_customer_sk = c_customer_sk or sr_customer_sk = c_customer_sk\n    * Join to store on ss_store_sk = s_store_sk or sr_store_sk = s_store_sk\n    * Join to item on ss_item_sk = i_item_sk or sr_item_sk = i_item_sk\n* Customer to Address: Link customer and customer_address by joining on c_current_addr_sk = ca_address_sk.",
          "options": {
            "chart": {
              "image": {
                "svg": {}
              }
            },
            "analysis": {
              "python": {}
            },
            "datasource": {
              "bigQueryMaxBilledBytes": "0"
            },
            "model": "MODEL_UNSPECIFIED"
          },
          "exampleQueries": [
            {
              "naturalLanguageQuestion": "Find customers who have returned items more than 20% more often than the average customer returns for a store in TN for the year 2000.",
              "sqlQuery": "WITH customer_total_return AS (\n  SELECT \n    sr_customer_sk AS ctr_customer_sk,\n    sr_store_sk AS ctr_store_sk,\n    SUM(sr_return_amt) AS ctr_total_return\n  FROM `bigquery-public-data.tpc_ds_1g.store_returns`\n  JOIN `bigquery-public-data.tpc_ds_1g.date_dim` ON sr_returned_date_sk = d_date_sk\n  WHERE d_year = 2000\n  GROUP BY sr_customer_sk, sr_store_sk\n)\nSELECT c_customer_id\nFROM customer_total_return ctr1\nJOIN `bigquery-public-data.tpc_ds_1g.store` ON s_store_sk = ctr1.ctr_store_sk\nJOIN `bigquery-public-data.tpc_ds_1g.customer` ON ctr_customer_sk = c_customer_sk\nWHERE ctr1.ctr_total_return > (\n  SELECT AVG(ctr_total_return) * 1.2\n  FROM customer_total_return ctr2\n  WHERE ctr1.ctr_store_sk = ctr2.ctr_store_sk\n)\nAND s_state = 'TN'\nORDER BY c_customer_id\nLIMIT 100;"
            },
            {
              "naturalLanguageQuestion": "Report the total extended sales price per item brand of manufacturer 128 for all sales in November (month 11).",
              "sqlQuery": "SELECT\n  dt.d_year,\n  item.i_brand_id AS brand_id,\n  item.i_brand AS brand,\n  SUM(ss_ext_sales_price) AS sum_agg\nFROM `bigquery-public-data.tpc_ds_1g.date_dim` AS dt\nJOIN `bigquery-public-data.tpc_ds_1g.store_sales` AS store_sales \n  ON dt.d_date_sk = store_sales.ss_sold_date_sk\nJOIN `bigquery-public-data.tpc_ds_1g.item` AS item \n  ON store_sales.ss_item_sk = item.i_item_sk\nWHERE\n  item.i_manufact_id = 128\n  AND dt.d_moy = 11\nGROUP BY\n  dt.d_year,\n  item.i_brand,\n  item.i_brand_id\nORDER BY\n  dt.d_year,\n  sum_agg DESC,\n  brand_id\nLIMIT 100;\n"
            },
            {
              "naturalLanguageQuestion": "List all the states with at least 10 customers who during January 2001 bought items with the price tag at least 20% higher than the average price of items in the same category.",
              "sqlQuery": "SELECT\n  a.ca_state AS state,\n  COUNT(*) AS cnt\nFROM `bigquery-public-data.tpc_ds_1g.customer_address` AS a\nJOIN `bigquery-public-data.tpc_ds_1g.customer` AS c\n  ON a.ca_address_sk = c.c_current_addr_sk\nJOIN `bigquery-public-data.tpc_ds_1g.store_sales` AS s\n  ON c.c_customer_sk = s.ss_customer_sk\nJOIN `bigquery-public-data.tpc_ds_1g.date_dim` AS d\n  ON s.ss_sold_date_sk = d.d_date_sk\nJOIN `bigquery-public-data.tpc_ds_1g.item` AS i\n  ON s.ss_item_sk = i.i_item_sk\nWHERE\n  d.d_month_seq = (\n    SELECT DISTINCT d_month_seq\n    FROM `bigquery-public-data.tpc_ds_1g.date_dim`\n    WHERE d_year = 2001 AND d_moy = 1\n  )\n  AND i.i_current_price > 1.2 * (\n    SELECT AVG(j.i_current_price)\n    FROM `bigquery-public-data.tpc_ds_1g.item` AS j\n    WHERE j.i_category = i.i_category\n  )\nGROUP BY a.ca_state\nHAVING COUNT(*) >= 10\nORDER BY cnt\nLIMIT 100;\n"
            }
          ],
          "datasourceReferences": {
            "bq": {
              "tableReferences": [
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "customer",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "customer_address",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "date_dim",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "item",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store_returns",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store_sales",
                  "schema": {}
                }
              ]
            }
          },
          "userFunctions": {}
        },
        "publishedContext": {
          "systemInstruction": "**Synonyms**\n* Customer: client, user, buyer\n* Revenue: sales, sales value, ss_ext_sales_price\n* Refunds: returns, sr_return_amt\n* Product: item\n* Address: customer location, customer address, home state\n\n**Key fields**\n* Identifiers: c_customer_id (Customer ID), i_item_id (Product ID), s_store_id (Store ID), ca_address_id (Address ID)\n* Timestamps: d_date (Date)\n* Metrics: ss_ext_sales_price (Total Revenue), ss_net_profit (Profit), sr_return_amt (Return Amount), i_current_price (Current Price)\n\n**Excluded Fields**\n* Surrogate Keys: Avoid using any fields ending in _sk (e.g., c_customer_sk, ss_item_sk, d_date_sk, ca_address_sk) in final text answers or displays.\n* Technical Metadata: ss_sold_time_sk, sr_return_time_sk, d_date_id.\n\n**Filtering and grouping**\n* Time: Use d_year for year-based filtering and d_moy for monthly grouping from the date_dim table.\n* Geography: Use s_state and s_store_name for store-based analysis; use ca_state, ca_city, and ca_county for customer home-location analysis.\n* Attributes: Use i_category and i_brand for product-level analysis.\n\n**Join relationships**\n* Sales & Returns: Link store_sales and store_returns by joining on both ss_item_sk = sr_item_sk and ss_ticket_number = sr_ticket_number.\n* Fact to Dimension: Combine fact tables (store_sales, store_returns) with dimension tables using surrogate keys:\n    * Join to date_dim on ss_sold_date_sk = d_date_sk or sr_returned_date_sk = d_date_sk\n    * Join to customer on ss_customer_sk = c_customer_sk or sr_customer_sk = c_customer_sk\n    * Join to store on ss_store_sk = s_store_sk or sr_store_sk = s_store_sk\n    * Join to item on ss_item_sk = i_item_sk or sr_item_sk = i_item_sk\n* Customer to Address: Link customer and customer_address by joining on c_current_addr_sk = ca_address_sk.",
          "options": {
            "chart": {
              "image": {
                "svg": {}
              }
            },
            "analysis": {
              "python": {}
            },
            "datasource": {
              "bigQueryMaxBilledBytes": "0"
            },
            "model": "MODEL_UNSPECIFIED"
          },
          "exampleQueries": [
            {
              "naturalLanguageQuestion": "Find customers who have returned items more than 20% more often than the average customer returns for a store in TN for the year 2000.",
              "sqlQuery": "WITH customer_total_return AS (\n  SELECT \n    sr_customer_sk AS ctr_customer_sk,\n    sr_store_sk AS ctr_store_sk,\n    SUM(sr_return_amt) AS ctr_total_return\n  FROM `bigquery-public-data.tpc_ds_1g.store_returns`\n  JOIN `bigquery-public-data.tpc_ds_1g.date_dim` ON sr_returned_date_sk = d_date_sk\n  WHERE d_year = 2000\n  GROUP BY sr_customer_sk, sr_store_sk\n)\nSELECT c_customer_id\nFROM customer_total_return ctr1\nJOIN `bigquery-public-data.tpc_ds_1g.store` ON s_store_sk = ctr1.ctr_store_sk\nJOIN `bigquery-public-data.tpc_ds_1g.customer` ON ctr_customer_sk = c_customer_sk\nWHERE ctr1.ctr_total_return > (\n  SELECT AVG(ctr_total_return) * 1.2\n  FROM customer_total_return ctr2\n  WHERE ctr1.ctr_store_sk = ctr2.ctr_store_sk\n)\nAND s_state = 'TN'\nORDER BY c_customer_id\nLIMIT 100;"
            },
            {
              "naturalLanguageQuestion": "Report the total extended sales price per item brand of manufacturer 128 for all sales in November (month 11).",
              "sqlQuery": "SELECT\n  dt.d_year,\n  item.i_brand_id AS brand_id,\n  item.i_brand AS brand,\n  SUM(ss_ext_sales_price) AS sum_agg\nFROM `bigquery-public-data.tpc_ds_1g.date_dim` AS dt\nJOIN `bigquery-public-data.tpc_ds_1g.store_sales` AS store_sales \n  ON dt.d_date_sk = store_sales.ss_sold_date_sk\nJOIN `bigquery-public-data.tpc_ds_1g.item` AS item \n  ON store_sales.ss_item_sk = item.i_item_sk\nWHERE\n  item.i_manufact_id = 128\n  AND dt.d_moy = 11\nGROUP BY\n  dt.d_year,\n  item.i_brand,\n  item.i_brand_id\nORDER BY\n  dt.d_year,\n  sum_agg DESC,\n  brand_id\nLIMIT 100;\n"
            },
            {
              "naturalLanguageQuestion": "List all the states with at least 10 customers who during January 2001 bought items with the price tag at least 20% higher than the average price of items in the same category.",
              "sqlQuery": "SELECT\n  a.ca_state AS state,\n  COUNT(*) AS cnt\nFROM `bigquery-public-data.tpc_ds_1g.customer_address` AS a\nJOIN `bigquery-public-data.tpc_ds_1g.customer` AS c\n  ON a.ca_address_sk = c.c_current_addr_sk\nJOIN `bigquery-public-data.tpc_ds_1g.store_sales` AS s\n  ON c.c_customer_sk = s.ss_customer_sk\nJOIN `bigquery-public-data.tpc_ds_1g.date_dim` AS d\n  ON s.ss_sold_date_sk = d.d_date_sk\nJOIN `bigquery-public-data.tpc_ds_1g.item` AS i\n  ON s.ss_item_sk = i.i_item_sk\nWHERE\n  d.d_month_seq = (\n    SELECT DISTINCT d_month_seq\n    FROM `bigquery-public-data.tpc_ds_1g.date_dim`\n    WHERE d_year = 2001 AND d_moy = 1\n  )\n  AND i.i_current_price > 1.2 * (\n    SELECT AVG(j.i_current_price)\n    FROM `bigquery-public-data.tpc_ds_1g.item` AS j\n    WHERE j.i_category = i.i_category\n  )\nGROUP BY a.ca_state\nHAVING COUNT(*) >= 10\nORDER BY cnt\nLIMIT 100;\n"
            }
          ],
          "datasourceReferences": {
            "bq": {
              "tableReferences": [
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "customer",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "customer_address",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "date_dim",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "item",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store_returns",
                  "schema": {}
                },
                {
                  "projectId": "bigquery-public-data",
                  "datasetId": "tpc_ds_1g",
                  "tableId": "store_sales",
                  "schema": {}
                }
              ]
            }
          },
          "userFunctions": {}
        }
      }
    },
    {
      "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_bdfccb95-e017-4e54-9bee-213bfe3af81a",
      "displayName": "The Look Ecommerce",
      "description": "You are a sample agent that has insights to the looks ecommerce dataset. Advanced analytics is not enabled for you.",
      "labels": {
        "sample-agent-signature": "sample_agent_looker_ecommerce_v1",
        "readonly": "true"
      },
      "createTime": "2026-05-26T07:53:50.553666503Z",
      "updateTime": "2026-05-26T07:53:51.113805825Z",
      "dataAnalyticsAgent": {
        "publishedContext": {
          "systemInstruction": "The agent has access to 4 core BigQuery tables for answering e-commerce and website analytics questions. All answers must be derived by querying and joining these tables:\n\n**A. Table and Primary Column Definitions**\n\n1.  **`events`**: Captures all user website activity (page views, clicks).\n    * **Primary Key:** `id` (event ID)\n    * **Key Columns:** `session_id`, `user_id`, `ip_address` (for unique visitors), `created_at` (timestamp), `uri` (full URL), `event_type`.\n\n2.  **`order_items`**: Contains line-item details for every purchase. **Use this for all financial and order-related questions.**\n    * **Primary Key:** `id`\n    * **Key Columns:** `order_id`, `user_id`, `inventory_item_id`, `sale_price` (raw revenue), `status`, `created_at` (order date).\n\n3.  **`products`**: Contains product catalog data.\n    * **Primary Key:** `id`\n    * **Key Columns:** `category`, `brand`, `department`, `retail_price`.\n\n4.  **`users`**: Contains customer demographics and account details.\n    * **Primary Key:** `id`\n    * **Key Columns:** `first_name`, `last_name`, `email`, `age`, `traffic_source`, `created_at` (signup date).\n\n**B. Join Logic and Data Connection Rules**\n\nThe agent MUST use standard SQL JOINs on the following column pairs to combine data:\n\n1.  **Customer Activity:**\n    * `order_items.user_id` = `users.id` (To link sales to customers)\n    * `events.user_id` = `users.id` (To link website activity to logged-in customers)\n\n2.  **Sales to Products:**\n    * `order_items` links to `products` indirectly via `inventory_item_id` (a join through an implicit inventory table is required, but for simple linking, assume a common `product_id` link for aggregation purposes). **Use `order_items.inventory_item_id` to group sales by product where direct linking is complex.**\n\n3.  **Website Events to Products:**\n    * To find which products were viewed: The `events.uri` column often contains the product ID. The agent must parse the `events.uri` to extract the ID and join it to `products.id`.\n\n**C. Metric Calculation Rules (Translate Natural Language to SQL Aggregation)**\n\nWhen a user asks for a metric, the agent must perform the following standard BigQuery SQL aggregation:\n\n| User Question Concept | SQL Aggregation Rule |\n| :--- | :--- |\n| **Total Revenue/Sales** | `SUM(t.sale_price)` on the `order_items` table. |\n| **Order Count** | `COUNT(DISTINCT t.order_id)` on the `order_items` table. |\n| **Item Count** | `COUNT(*)` on the `order_items` table. |\n| **Average Item Price** | `AVG(t.sale_price)` on the `order_items` table. |\n| **Total Users/Customers** | `COUNT(DISTINCT t.id)` on the `users` table. |\n| **Unique Visitors** | `COUNT(DISTINCT t.ip_address)` on the `events` table. |\n| **Session Count** | `COUNT(DISTINCT t.session_id)` on the `events` table. |\n\n**D. Date Handling**\n\n* Always use the `created_at` column from the relevant table for time-based filtering and grouping:\n    * Sales: `order_items.created_at`\n    * Website Traffic: `events.created_at`\n    * User Signups: `users.created_at`\n* When using a date for your query, always only use the date, dont use the timestamp. TIMESTAMP_TRUNC is not necessary to be used, make sure that the resultset does **NOT** include a timestamp.",
          "options": {
            "chart": {
              "image": {
                "svg": {}
              }
            },
            "analysis": {
              "python": {}
            },
            "datasource": {
              "bigQueryMaxBilledBytes": "0"
            },
            "model": "MODEL_UNSPECIFIED"
          },
          "exampleQueries": [
            {
              "naturalLanguageQuestion": "What is the total revenue for each product category this year?",
              "sqlQuery": "SELECT products.category, SUM(order_items.sale_price) AS total_revenue\nFROM bigquery-public-data.thelook_ecommerce.order_items AS order_items\nINNER JOIN bigquery-public-data.thelook_ecommerce.products AS products\n  ON order_items.product_id = products.id\nWHERE\n  TIMESTAMP_TRUNC(order_items.created_at, YEAR)\n  = TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), YEAR)\nGROUP BY products.category\nORDER BY SUM(order_items.sale_price) DESC;"
            },
            {
              "naturalLanguageQuestion": "How many unique customers from the 'Organic' traffic source are over the age of 30?",
              "sqlQuery": "SELECT COUNT(DISTINCT id) AS customer_count \nFROM bigquery-public-data.thelook_ecommerce.users \nWHERE traffic_source = 'Organic' AND age > 30\n"
            },
            {

In [12]:
# @title Update Data Agent

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"

payload = {
    "description": "This is the latest description of data_agent.",
    "data_analytics_agent": {
        "published_context": {
            "datasource_references": datasource_references,
            "system_instruction": system_instruction,
        }
    },
}

fields = ["description", "data_analytics_agent"]
params = {"updateMask": ",".join(fields)}

data_agent_response = requests.patch(
    data_agent_url, headers=headers, params=params, json=payload
)

if data_agent_response.status_code == 200:
  print("Data Agent updated successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error Updating Data Agent: {data_agent_response.status_code}")
  print(data_agent_response.text)

Data Agent updated successfully!
{
  "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/operations/operation-1779783948996-652b43e0e9144-a29f8dff-5f3db8c2",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.geminidataanalytics.v1beta.OperationMetadata",
    "createTime": "2026-05-26T08:25:49.417760881Z",
    "target": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd",
    "verb": "update",
    "requestedCancellation": false,
    "apiVersion": "v1beta"
  },
  "done": false
}

In [15]:
# @title [Agent Sharing] Set IAM Policy for Data Agent


"""PLEASE NOTE THIS API CALLS OVERRIDES EXISTING PERMISSION FOR THE RESOURCE.

For preserving existing policy in practise call Get IAM policy to fetch existing
policy and pass it along with additional changes in the call to Set IAM Policy
"""

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
users = "gutivanaliefs@gmail.com"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}:setIamPolicy"


# Request body
payload = {
    "policy": {
        "bindings": [{
            "role": "roles/geminidataanalytics.dataAgentEditor",
            "members": [f"user:{i.strip()}" for i in users.split(",")],
        }]
    }
}

data_agent_response = requests.post(
    data_agent_url, headers=headers, json=payload
)

if data_agent_response.status_code == 200:
  print("IAM Policy set successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error setting IAM policy: {data_agent_response.status_code}")
  print(data_agent_response.text)

IAM Policy set successfully!
{
  "version": 1,
  "etag": "BwZStEEa/2Q=",
  "bindings": [
    {
      "role": "roles/geminidataanalytics.dataAgentEditor",
      "members": [
        "user:Gutivanaliefs@gmail.com"
      ]
    }
  ]
}

In [16]:
# @title [Agent Sharing] Get IAM Policy for Data Agent

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}:getIamPolicy"

# Request body
payload = {
    "resource": (
        f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
    )
}

data_agent_response = requests.post(
    data_agent_url, headers=headers, json=payload
)

if data_agent_response.status_code == 200:
  print("IAM Policy fetched successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error fetching IAM policy: {data_agent_response.status_code}")
  print(data_agent_response.text)

IAM Policy fetched successfully!
{
  "version": 1,
  "etag": "BwZStEEa/2Q=",
  "bindings": [
    {
      "role": "roles/geminidataanalytics.dataAgentEditor",
      "members": [
        "user:Gutivanaliefs@gmail.com"
      ]
    }
  ]
}

In [ ]:
# @title [Soft Delete] Delete Data Agent

# fmt: off
data_agent_id = "data_agent_1"  # @param {type:"string"}
# fmt: on

data_agent_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"

data_agent_response = requests.delete(data_agent_url, headers=headers)

if data_agent_response.status_code == 200:
  print("Data Agent deleted successfully!")
  print(json.dumps(data_agent_response.json(), indent=2))
else:
  print(f"Error Deleting Data Agent: {data_agent_response.status_code}")
  print(data_agent_response.text)

# Data Chat Service

In [17]:
# @title Create Conversation

# fmt: off
data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
conversation_id = "conversation_1"  # @param {type:"string"}
# fmt: on

conversation_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/conversations"

conversation_payload = {
    "agents": [
        f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
    ],
    "name": (
        f"projects/{billing_project}/locations/{location}/conversations/{conversation_id}"
    ),
}
params = {"conversation_id": conversation_id}

conversation_response = requests.post(
    conversation_url, headers=headers, params=params, json=conversation_payload
)

if conversation_response.status_code == 200:
  print("Conversation created successfully!")
  print(json.dumps(conversation_response.json(), indent=2))
else:
  print(f"Error creating Conversation: {conversation_response.status_code}")
  print(conversation_response.text)

Conversation created successfully!
{
  "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/conversations/conversation_1",
  "agents": [
    "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
  ],
  "createTime": "2026-05-26T08:27:07.670170Z",
  "lastUsedTime": "2026-05-26T08:27:07.936004Z"
}

In [18]:
# @title Get Conversation

# fmt: off
conversation_id = "conversation_1"  # @param {type:"string"}
# fmt: on

conversation_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/conversations/{conversation_id}"

conversation_response = requests.get(conversation_url, headers=headers)

# Handle the response
if conversation_response.status_code == 200:
  print("Conversation fetched successfully!")
  print(json.dumps(conversation_response.json(), indent=2))
else:
  print(
      f"Error while fetching conversation: {conversation_response.status_code}"
  )
  print(conversation_response.text)

Conversation fetched successfully!
{
  "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/conversations/conversation_1",
  "agents": [
    "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
  ],
  "createTime": "2026-05-26T08:27:07.670170Z",
  "lastUsedTime": "2026-05-26T08:27:07.936004Z"
}

In [19]:
# @title List Conversation

conversation_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/conversations"


conversation_response = requests.get(conversation_url, headers=headers)

# Handle the response
if conversation_response.status_code == 200:
  print("Conversation fetched successfully!")
  print(json.dumps(conversation_response.json(), indent=2))
else:
  print(
      f"Error while fetching conversation: {conversation_response.status_code}"
  )
  print(conversation_response.text)

Conversation fetched successfully!
{
  "conversations": [
    {
      "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/conversations/conversation_1",
      "agents": [
        "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
      ],
      "createTime": "2026-05-26T08:27:07.670170Z",
      "lastUsedTime": "2026-05-26T08:27:07.936004Z"
    },
    {
      "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/conversations/ccea0272-d367-42b8-a1e0-a2a1b9bed211",
      "agents": [
        "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
      ],
      "createTime": "2026-05-26T07:59:06.795473Z",
      "lastUsedTime": "2026-05-26T08:03:55.340Z",
      "labels": {
        "host": "bigquery"
      }
    },
    {
      "name": "projects/project-4edfdecd-6192-4f0d-be4/locations/global/conversations/1572dff6-c309-4665-a0d5-f8e504104f40",
      "agents": [
        "projects/project-4edfdecd-6192-4f0d-be4/locations/global/dataAgents/agent_2b34caf2-fe71-432b-885d-545f2b934ddd"
      ],
      "createTime": "2026-05-26T07:58:24.304317Z",
      "lastUsedTime": "2026-05-26T07:58:41.222Z",
      "labels": {
        "host": "bigquery"
      }
    }
  ]
}

In [ ]:
# @title Delete Conversation

# fmt: off
conversation_id = "conversation_1"  # @param {type:"string"}
# fmt: on

conversation_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/conversations/{conversation_id}"

conversation_response = requests.delete(conversation_url, headers=headers)

# Handle the response
if conversation_response.status_code == 200:
  print("Conversation deleted successfully!")
  print(json.dumps(conversation_response.json(), indent=2))
else:
  print(
      f"Error while deleting conversation: {conversation_response.status_code}"
  )
  print(conversation_response.text)

In [20]:
# @title Streaming Chat Messages


def is_json(str):
  try:
    json_object = json_lib.loads(str)
  except ValueError:
    return False
  return True


def handle_text_response(resp):
  parts = resp["parts"]
  full_text = "".join(parts)
  if "\n" not in full_text and len(full_text) > 80:
    wrapped_text = textwrap.fill(full_text, width=80)
    print(wrapped_text)
  else:
    print(full_text)


def get_property(data, field_name, default=""):
  return data[field_name] if field_name in data else default


def display_schema(data):
  fields = data["fields"]
  df = pd.DataFrame({
      "Column": map(lambda field: get_property(field, "name"), fields),
      "Type": map(lambda field: get_property(field, "type"), fields),
      "Description": map(
          lambda field: get_property(field, "description", "-"), fields
      ),
      "Mode": map(lambda field: get_property(field, "mode"), fields),
  })
  display(df)


def display_section_title(text):
  display(HTML(f"<h2>{text}</h2>"))


def format_bq_table_ref(table_ref):
  return "{}.{}.{}".format(
      table_ref["projectId"], table_ref["datasetId"], table_ref["tableId"]
  )


def format_looker_table_ref(table_ref):
  return "lookmlModel: {}, explore: {}".format(
      table_ref["lookmlModel"], table_ref["explore"]
  )


def display_datasource(datasource):
  source_name = ""

  if "studioDatasourceId" in datasource:
    source_name = datasource["studioDatasourceId"]
  elif "lookerExploreReference" in datasource:
    source_name = format_looker_table_ref(datasource["lookerExploreReference"])
  else:
    source_name = format_bq_table_ref(datasource["bigqueryTableReference"])

  print(source_name)
  if "schema" in datasource:
    display_schema(datasource["schema"])


def handle_schema_response(resp):
  if "query" in resp and "question" in resp["query"]:
    print(resp["query"]["question"])
  elif "result" in resp:
    display_section_title("Schema resolved")
    print("Data sources:")
    for datasource in resp["result"]["datasources"]:
      display_datasource(datasource)


def handle_data_response(resp):
  if "query" in resp:
    query = resp["query"]
    display_section_title("Retrieval query")
    if "name" in query:
      print("Query name: {}".format(query["name"]))
    if "question" in query:
      print("Question: {}".format(query["question"]))
    if "datasources" in query:
      print("Data sources:")
      for datasource in query["datasources"]:
        display_datasource(datasource)
  elif "generatedSql" in resp:
    display_section_title("SQL generated")
    print(resp["generatedSql"])
  elif "result" in resp:
    display_section_title("Data retrieved")

    fields = map(
        lambda field: get_property(field, "name"),
        resp["result"]["schema"]["fields"],
    )
    dict = {}

    for field in fields:
      dict[field] = [get_property(el, field) for el in resp["result"]["data"]]

    display(pd.DataFrame(dict))


def handle_chart_response(resp):
  if "query" in resp and "instructions" in resp["query"]:
    print(resp["query"]["instructions"])
  elif "result" in resp:
    vegaConfig = resp["result"]["vegaConfig"]
    alt.Chart.from_json(json_lib.dumps(vegaConfig)).display()


def handle_error(resp):
  display_section_title("Error")
  print("Code: {}".format(resp["code"]))
  print("Message: {}".format(resp["message"]))


def get_stream(url, json):
  s = requests.Session()

  acc = ""

  with s.post(url, json=json, headers=headers, stream=True) as resp:
    for line in resp.iter_lines():
      if not line:
        continue

      decoded_line = str(line, encoding="utf-8")

      if decoded_line == "[{":
        acc = "{"
      elif decoded_line == "}]":
        acc += "}"
      elif decoded_line == ",":
        continue
      else:
        acc += decoded_line

      if not is_json(acc):
        continue

      data_json = json_lib.loads(acc)

      if "systemMessage" not in data_json:
        if "error" in data_json:
          handle_error(data_json["error"])
        continue

      if "text" in data_json["systemMessage"]:
        handle_text_response(data_json["systemMessage"]["text"])
      elif "schema" in data_json["systemMessage"]:
        handle_schema_response(data_json["systemMessage"]["schema"])
      elif "data" in data_json["systemMessage"]:
        handle_data_response(data_json["systemMessage"]["data"])
      elif "chart" in data_json["systemMessage"]:
        handle_chart_response(data_json["systemMessage"]["chart"])
      else:
        colored_json = highlight(
            acc, lexers.JsonLexer(), formatters.TerminalFormatter()
        )
        print(colored_json)
      print("\n")
      acc = ""

In [23]:
# @title [Stateful] Chat using Conversation

data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
conversation_id = "conversation_1"  # @param {type:"string"}

# fmt: off
question = "Make a bar graph for the top 5 product, **Total Revenue** - Ranked by the sum of sales prices."  # @param {type:"string"}
# fmt: on

chat_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}:chat"

# Construct the payload
chat_payload = {
    "parent": f"projects/{billing_project}/locations/global",
    "messages": [{"userMessage": {"text": question}}],
    "conversation_reference": {
        "conversation": (
            f"projects/{billing_project}/locations/{location}/conversations/{conversation_id}"
        ),
        "data_agent_context": {
            "data_agent": (
                f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
            ),
        },
    },
}
# Call get_stream method to stream the response
get_stream(chat_url, chat_payload)

Analyzing contextRetrieved context for 7 tables.


My Thought Process for Generating the Top 5 Products by Revenue Bar
ChartAlright, let's break down how I arrived at the solution for your request to
visualize the top 5 products by total revenue. The core of your request is
clear: you want a bar graph showing the top 5 products based on their total
revenue, which you've defined as the sum of their sales prices. Looking at the
available schema, I see two key tables: `products`: This will give me the
`product_id` and the `product_name` – essential for labeling my chart.
`order_items`: This table contains the `product_id` and, crucially, the
`sale_price` for each item sold. My immediate thought is that I need to connect
these two pieces of information. This means I'll have to perform a `JOIN`
operation. Specifically, an `INNER JOIN` makes the most sense because I only
care about order items that actually correspond to a product in the `products`
table. The join condition will naturally be `products.id =
order_items.product_id`. Once I have the sales prices linked to product names,
the next step is to aggregate the revenue for each product. This calls for a
`GROUP BY` clause. I'll group by both `product_id` and `product_name`. Grouping
by `product_id` ensures uniqueness, and including `product_name` allows me to
select it directly in the final query without needing another join or subquery
later. Within each group (i.e., for each product), I need to calculate the total
revenue. This is a straightforward `SUM()` aggregation on the `sale_price`
column. I'll alias this sum as `total_revenue` for clarity. Now, the request
specifically asks for the top 5. To achieve this, I need to `ORDER BY` the
calculated `total_revenue` in `DESC`ending order. After sorting, I'll simply
`LIMIT` the results to `5`. So, the SQL query that emerges from this logic is
precisely what I've laid out: ```sql SELECT products.id AS product_id,
products.name AS product_name, SUM(order_items.sale_price) AS total_revenue FROM
`project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products INNER JOIN
`project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items ON
products.id = order_items.product_id GROUP BY product_id, product_name ORDER BY
total_revenue DESC LIMIT 5; ``` I then reviewed the constraints: "Make a bar
graph" is directly addressed by the charting requirement. "Top 5 product" is
handled by the `ORDER BY ... DESC LIMIT 5`. "Total Revenue - Ranked by the sum
of sales prices" is precisely what the `SUM(sale_price)` and subsequent ordering
achieve. Regarding AI functions, I checked if any were explicitly mentioned or
if the prompt implied their use. Since the query is standard SQL and doesn't
involve BigQuery ML or other advanced AI features, I concluded that loading a
specific AI skill like BigQuery AI wasn't necessary for this particular task.
It's good practice to only load what's needed. With the SQL query confirmed and
the logic validated against the requirements, my plan is to execute this SQL to
fetch the necessary data and then use a charting library, likely Altair, to
generate the requested bar chart from the returned data. The final output will
include both the data itself and the visualization.


My Thought Process for Generating the Top 5 Products Revenue Bar GraphAlright,
so the request is clear: I need to visualize the top 5 products based on their
total revenue. The output should be a bar graph, and I've already done the heavy
lifting by running a SQL query named `top_5_products_revenue`. This query has
conveniently provided me with the `product_id`, `product_name`, and
`total_revenue` for those top contenders. My next step is to translate this data
into a compelling visual. The tool of choice here is Altair, a fantastic Python
library for declarative statistical visualization. The user specifically wants
the output as a JSON string representing the Vega-Lite specification, which
means I'll need to use Python to build this spec and then print it. The
requirements are pretty specific: I must import `altair` and `json`. The final
output needs to be a JSON string. Crucially, the `alt.Chart()` function needs to
reference the `data_result_name`, which is `top_5_products_revenue`. I should
use shorthand type annotations for clarity (like `:N` for nominal/categorical
and `:Q` for quantitative/numerical). I need to include `usermeta` containing
both the `data_result_name` and a `chart_id` (though the `chart_id` wasn't
explicitly provided, I'll assume it's something I need to generate or can use a
placeholder for). A descriptive title for the chart and clear labels for the
axes are essential for interpretability. Now, regarding the chart itself: a bar
chart is requested. The instructions mention that horizontal bars are sometimes
better for long product names, but the default preference is vertical bars
unless specified otherwise. Given this, I'll stick with a vertical bar chart.
The x-axis will represent the `product_name`, which is a categorical or nominal
variable, hence `:N`. The y-axis will represent `total_revenue`, a quantitative
variable, hence `:Q`. So, my plan is quite straightforward: 1. I'll construct
the Python code that orchestrates all these requirements. This will involve
importing the necessary libraries, creating the Altair chart object, mapping the
data columns to the appropriate visual encoding (x and y axes, color, etc.),
adding a title, and then serializing the chart specification to a JSON string.
2. Once the code is ready, I'll execute it using the `google:python_interpreter`
to ensure it runs correctly and produces the desired JSON output. 3. Finally,
I'll present this JSON output as the solution. Essentially, I'm taking the
structured data from my SQL query and using Altair's declarative approach to
build a visual representation that highlights the revenue performance of the top
5 products. The emphasis is on generating a precise, well-formatted JSON output
that conforms to all the specified requirements.


My Thought Process for Generating the Final ResponseAlright, I've got the data
and the visualization components ready. My next step is to construct the
complete, polished output for the user. My internal objective is to present a
comprehensive answer that not only fulfills the user's request but also offers
valuable context and interpretation. Specifically, I recall the user's explicit
requirement: a bar graph depicting the top 5 products, meticulously ranked by
their total revenue. I have successfully processed the underlying data and now
have that result available as `top_5_products_revenue`. Concurrently, I've
generated the corresponding visualization, which I've identified with the chart
ID `top_5_products_revenue_bar_chart`. My strategy for structuring this final
response is deliberate and designed for maximum clarity and utility. I will
begin with a concise Your Summary that encapsulates the essence of the findings.
This will be followed by the direct presentation of the `top_5_products_revenue`
data itself, allowing for granular inspection. Then, I will integrate the
`top_5_products_revenue_bar_chart`, providing the visual representation that was
requested. Crucially, I will conclude with a section dedicated to Insights,
where I'll offer interpretations and highlight the key takeaways derived from
both the data and the chart. This structured approach ensures that the user can
easily digest the information, understand the underlying numbers, visualize the
trends, and gain actionable intelligence.


The following data and chart show the top 5 products in terms of total revenue,
calculated by summing the sales prices of all items sold for each product.

Data sources:
project-4edfdecd-6192-4f0d-be4.ecommerce.order_items
project-4edfdecd-6192-4f0d-be4.ecommerce.products

SELECT
    products.id AS product_id,
    products.name AS product_name,
    SUM(order_items.sale_price) AS total_revenue
FROM
    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products
INNER JOIN
    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items
    ON products.id = order_items.product_id
GROUP BY
    product_id,
    product_name
ORDER BY
    total_revenue DESC
LIMIT 5;

,product_id,product_name,total_revenue
0,24110,Woolrich Arctic Parka DF,13860
1,23989,The North Face Freedom Mens Ski Pants 2013,12642
2,24899,Nike Jordan Retro 11 Bred Bootie Socks,9030
3,2557,Canada Goose Women's Mystique,9000
4,24201,Mens Nike AirJordan Varsity Hoodie Jacket Grey...,8127

Data sources:
project-4edfdecd-6192-4f0d-be4.ecommerce.order_items
project-4edfdecd-6192-4f0d-be4.ecommerce.products

SELECT
    products.id AS product_id,
    products.name AS product_name,
    SUM(order_items.sale_price) AS total_revenue
FROM
    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products
INNER JOIN
    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items
    ON products.id = order_items.product_id
GROUP BY
    product_id,
    product_name
ORDER BY
    total_revenue DESC
LIMIT 5;

alt.Chart(...)

### Insights

*   **Revenue Leader:** The **Woolrich Arctic Parka DF** is the highest-grossing product, generating **$13,860** in total revenue.
*   **High-Value Apparel:** Most of the top-performing products are high-value winter wear or sports apparel, such as the **The North Face Freedom Mens Ski Pants** and the **Canada Goose Women's Mystique** parka.
*   **Revenue Concentration:** These top 5 products alone have generated significant revenue, ranging from approximately $8,100 to nearly $14,000 each.


What are the top 5 products by total units sold?Which product brands generate
the most revenue?Predict the revenue for the top-selling product for the next 6
months.

In [29]:
# @title [Stateful] Chat using Data Agent

data_agent_id = "agent_2b34caf2-fe71-432b-885d-545f2b934ddd"  # @param {type:"string"}
# fmt: off
question = "Make a bar graph for the top 5 product, **Total Revenue** - Ranked by the sum of sales prices."  # @param {type:"string"}
# fmt: on

chat_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}:chat"

# Construct the payload
chat_payload = {
    "parent": f"projects/{billing_project}/locations/global",
    "messages": [{"userMessage": {"text": question}}],
    "data_agent_context": {
        "data_agent": (
            f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
        ),
    },
}

# if looker_selected:
  # chat_payload["data_agent_context"]["credentials"] = looker_credentials

# Call get_stream method to stream the response
get_stream(chat_url, chat_payload)

Code: 401
Message: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

In [26]:
# @title [Stateless] Chat using Inline Context

chat_url = (
    f"{base_url}/{api_version}/projects/{billing_project}/locations/global:chat"
)

# fmt: off
question = "Make a bar graph for the top 5 product, **Total Revenue** - Ranked by the sum of sales prices."  # @param {type:"string"}
# fmt: on

datasource_refs = dict(datasource_references)

# use credentials in datasource_references only in stateless chat request using inline context
# if looker_selected:
#   datasource_refs["looker"] = {
#       **datasource_refs["looker"],
#       "credentials": looker_credentials,
#   }

# Construct the payload
chat_payload = {
    "parent": f"projects/{billing_project}/locations/global",
    "messages": [{"userMessage": {"text": question}}],
    "inline_context": {
        "datasource_references": datasource_refs,
        "options": {
            "analysis": {
                # Optional - if wanting to use advanced analysis with python.
                # Default is False.
                "python": {"enabled": False}
            }
        },
    },
}

if bq_selected:
  if use_example_queries:
    chat_payload["inline_context"]["example_queries"] = example_queries
  if use_glossary_terms:
    chat_payload["inline_context"]["glossary_terms"] = glossary_terms
elif looker_selected and use_looker_golden_queries:
  chat_payload["inline_context"][
      "looker_golden_queries"
  ] = looker_golden_queries

# Call get_stream method to stream the response
get_stream(chat_url, chat_payload)

Analyzing contextRetrieved context for 7 tables.


My Thought Process for Generating the Top 5 Products by Revenue Bar GraphThe
user's request is quite specific: they want a bar graph visualizing the top 5
products based on their total revenue. My first priority is to understand how
"total revenue" is defined. Consulting the provided glossary, I see that "Total
revenue" is explicitly defined as "the sum of sales prices." This is a crucial
piece of information. Next, I need to identify the data sources required to
calculate this. To get the `sale_price`, I know I'll need to look at the
`order_items` table. To identify the products themselves and get their names,
I'll need to join this with a table that contains product information. The
`products` table seems like the most direct fit for this, as it contains product
`id` and `name`. Alternatively, `inventory_items` might also have product
information, but `products` feels more aligned with the direct "product"
concept. So, my plan is to join `order_items` with `products` using the
`product_id`. Now, for the execution plan: 1. Review Example Queries: I'll
quickly scan the available example queries to see if there's anything that
closely matches or can be easily adapted. Example 0 deals with categories and
revenue, which is similar in concept, so I can adapt its structure. 2. Table
Identification: Based on the above, I've confirmed that `ecommerce.order_items`
(for `sale_price`) and `ecommerce.products` (for `product_id` and `name`) are
the tables I need. 3. SQL Generation: The core logic will involve: Selecting the
product identifier and name from the `products` table. Calculating the sum of
`sale_price` from the `order_items` table. Joining `order_items` and `products`
on their respective `product_id` and `id` columns. Grouping the results by
product ID and name to aggregate the sales for each unique product. Ordering
these aggregated revenues in descending order to identify the top performers.
Limiting the results to the top 5. This leads me to construct the following SQL
query: ```sql SELECT p.id AS product_id, p.name AS product_name,
SUM(oi.sale_price) AS total_revenue FROM
`project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS oi JOIN
`project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS p ON oi.product_id = p.id
GROUP BY p.id, p.name ORDER BY total_revenue DESC LIMIT 5; ``` 4. Ambiguity
Check: The prompt specifies "top 5 product." I've ensured that I'm using both
`product_id` and `product_name` in my selection and grouping to provide a
complete and unambiguous representation of the product. 5. Skill Loading (Self-
Correction): I notice a mention of BigQuery AI. While I'm aware of advanced
AI/ML queries, this request is a straightforward SQL aggregation. Therefore, I
determine that this specific skill is not strictly necessary for this task. 6.
Execution: Once the SQL is constructed and validated, I'll proceed to execute it
against the database. 7. Visualization: The user explicitly requested a "bar
graph." My final output will be presented in this visual format. 8. Final Output
& Citations: I will then present the bar graph along with any necessary
citations, ensuring I reference the glossary definition of "revenue" as used in
my calculation. In essence, my thought process is a systematic approach: define
the goal, understand the definitions, identify data sources, plan the query
logic, construct the SQL, verify against requirements, and finally present the
result in the requested format, ensuring all constraints and definitions are
met.


My Thought Process for Generating the Top 5 Products Revenue Bar ChartAlright,
so the core request is straightforward: I need to visualize the top 5 products
based on their total revenue. I've already done the heavy lifting on the data
side by executing the SQL query, and the results are sitting right there in
`top_5_products_revenue`, which is conveniently structured with `product_id`,
`product_name`, and `total_revenue`. My next step is to leverage the
`google:python_interpreter` tool to craft the Python code for generating this
bar chart. My plan is to use `altair` for this visualization. I'll be feeding it
the `top_5_products_revenue` data. Now, regarding the chart orientation, the
instructions are quite clear: "orient the bars vertically unless instructed
otherwise." While I immediately recognized that long product names could lead to
overlap with vertical bars, I'm sticking to the directive. If it ends up looking
messy, that's something I might flag or consider for a follow-up, but for this
iteration, vertical it is. For the axes, I'll map `product_name` to the x-axis
and `total_revenue` to the y-axis. I'll use the shorthand types, so
`product_name:N` (nominal) and `total_revenue:Q` (quantitative). I also want to
include the `product_id` in the tooltip. Even though the prompt doesn't
explicitly demand it, including it is good practice for completeness, as it
provides unique identification. Before diving headfirst into coding, I need to
perform a quick "MANDATORY DATA SUFFICIENCY CHECK" to ensure I'm on the right
track. 1. AI Functions? No, I'm not calling any specific AI functions here, just
generating visualization code. 2. Explicit Request? Yes, the user explicitly
asked for a "bar graph." 3. Fewer than 4 rows? No, my data has 5 rows, which is
sufficient. 4. Simple comparison? While it involves comparison, it's primarily
an explicit visualization request, so I'm proceeding. Now, let's refine the
Python code. I'll start by importing `altair` and `json`. I'll define the
`data_result_name` as `'top_5_products_revenue'` and give my chart a unique
`chart_id`, `'top_5_products_revenue_chart'`. The `altair` code will look
something like this: ```python import altair as alt import json data_result_name
= 'top_5_products_revenue' chart_id = 'top_5_products_revenue_chart' chart =
alt.Chart(data_result_name).mark_bar().encode( x=alt.X('product_name:N',
title='Product Name', sort=alt.EncodingSortField(field='total_revenue',
order='descending')), y=alt.Y('total_revenue:Q', title='Total Revenue'),
tooltip=[ alt.Tooltip('product_id:N', title='Product ID'),
alt.Tooltip('product_name:N', title='Product Name'),
alt.Tooltip('total_revenue:Q', title='Total Revenue', format='$,.2f') ]
).properties( title='Top 5 Products by Total Revenue', width=600, height=400,
usermeta={"data_result_name": data_result_name, "chart_id": chart_id} )
print(json.dumps(chart.to_dict())) ``` I've specifically added
`sort=alt.EncodingSortField(field='total_revenue', order='descending')` to the
x-axis encoding. This ensures that the bars are displayed in descending order of
revenue, which is crucial for identifying the "top" products. I've also
formatted the `total_revenue` in the tooltip to show it as currency with two
decimal places (`format='$,.2f'`), which is a standard and user-friendly way to
present financial data. The `usermeta` is included as required for associating
the chart with its data source and a unique ID. Finally, I'll print the JSON
representation of the chart. One minor thought crossed my mind: the
`product_id`. While I've included it in the tooltip, I'm not using it as a
primary encoding element. Given that `product_name` is what we're displaying on
the axis, and assuming product names are reasonably unique for this dataset,
`product_id`'s role here is mainly for disambiguation in the tooltip if needed,
or as a direct identifier. It's not being used to group or differentiate bars
because the request is about the top 5 products, and `product_name` serves that
purpose for the visual. I also quickly scanned the glossary and citation rules.
I noticed "revenue" is mapped to "total sales" in the glossary, which aligns
perfectly with my understanding of `total_revenue`. The example queries also
show similar data manipulation patterns for revenue analysis, reinforcing my
approach. I'll use shorthand types in the final code: `product_name:N` for
nominal and `total_revenue:Q` for quantitative. This is just for conciseness in
the specification.


My Thought Process for Generating the Final AnswerAlright, I've got the data and
the chart ready. My next step is to assemble all the pieces into a comprehensive
final answer. This involves several key components that I need to ensure are
present and accurate. First and foremost, I need to provide a clear summary of
the findings. This will encapsulate the core insights derived from the analysis.
Next, I must include the data result tag. This is crucial for programmatic
access to the primary numerical outcome of the analysis. Following that, I'll
add the chart tag, indicating where the visual representation of the data
resides. Then comes the insights section. This is where I'll articulate the key
takeaways and observations that emerge from the data and the chart. I've already
identified some significant points: The top product generating the most revenue
is the "Woolrich Arctic Parka DF," bringing in a substantial $13,860.00. "The
North Face Freedom Mens Ski Pants 2013" is performing very strongly, coming in
as a close second. It's evident that the highest-revenue generating products are
primarily high-value winter apparel, such as parkas and ski pants, along with
popular brand-name items like Nike Jordan and Canada Goose. To further enrich
the analysis and guide potential future investigations, I need to formulate
relevant follow-up questions. I've brainstormed a few that seem pertinent: 1.
What are the top 5 brands, ranked by their total revenue contribution? 2. Which
specific product category is the most significant driver of overall revenue? 3.
Can we predict the revenue for the top 5 products over the next three months?
This would likely involve more advanced BQML (BigQuery ML) capabilities. Before
I finalize everything, I need to perform a critical double-check. The user
specifically asked for the "sum of sales prices." I need to confirm that my
calculation indeed used `SUM` and not `DISTINCT`. Yes, I’ve confirmed I used
`SUM` for the sales prices, which aligns perfectly with the request. Finally, I
must meticulously ensure that all citations are correctly formatted. I have two
primary sources to cite: A glossary term for "revenue," which I've indexed as 0.
An example query that illustrates the logic for revenue calculation, also
indexed as 0. I've reviewed the required citation format: `<citation_source
source_id="SOURCE_ID" source_type="SOURCE_TYPE">XML_METADATA</citation_source>`
and `<cite_start source_id="SOURCE_ID" cite_id="CITE_ID">cited text<cite_end
cite_id="CITE_ID">`. Here's how I'll structure the source citations: For the
glossary term "revenue": ```xml <citation_source source_id="g_rev"
source_type="glossary_term"> <title>Glossary: revenue</title>
<glossary_term_index>0</glossary_term_index> </citation_source> ``` And for the
example query: ```xml <citation_source source_id="ex_q0"
source_type="example_query"> <title>Verified Query: Total Revenue by
Category</title> <example_query_index>0</example_query_index> </citation_source>
``` With all these elements in place and verified, I'm ready to construct the
final answer.


This answer provides the top 5 products ranked by their total revenue, along with a visualization of their sales performance.

        The following data and chart represent the total revenue (sum of sales prices) for the leading products in the catalog, calculated using a logic similar to the verified category revenue query.

Data sources:
project-4edfdecd-6192-4f0d-be4.ecommerce.order_items
project-4edfdecd-6192-4f0d-be4.ecommerce.products

SELECT
    products.id AS product_id,
    products.name AS product_name,
    SUM(order_items.sale_price) AS total_revenue
FROM
    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items
INNER JOIN
    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products
    ON order_items.product_id = products.id
GROUP BY
    product_id,
    product_name
ORDER BY
    total_revenue DESC
LIMIT 5;

,product_id,product_name,total_revenue
0,24110,Woolrich Arctic Parka DF,13860
1,23989,The North Face Freedom Mens Ski Pants 2013,12642
2,24899,Nike Jordan Retro 11 Bred Bootie Socks,9030
3,2557,Canada Goose Women's Mystique,9000
4,24201,Mens Nike AirJordan Varsity Hoodie Jacket Grey...,8127

Data sources:
project-4edfdecd-6192-4f0d-be4.ecommerce.order_items
project-4edfdecd-6192-4f0d-be4.ecommerce.products

SELECT
    products.id AS product_id,
    products.name AS product_name,
    SUM(order_items.sale_price) AS total_revenue
FROM
    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items
INNER JOIN
    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products
    ON order_items.product_id = products.id
GROUP BY
    product_id,
    product_name
ORDER BY
    total_revenue DESC
LIMIT 5;

alt.Chart(...)

### Insights

*   **Leading Product**: The "Woolrich Arctic Parka DF" is the top-performing product, generating **$13,860.00** in total revenue.
*   **High-Value Items**: The list is dominated by premium outerwear and athletic brands, including "The North Face", "Nike", and "Canada Goose".
*   **Revenue Concentration**: There is a notable gap between the top two products and the rest of the top five, suggesting these specific winter items are significant drivers of sales value.


What are the top 5 brands by total revenue?Which product categories generate the
highest revenue?Predict the revenue for the top 5 products for the next quarter
based on historical trends.

In [27]:
# @title List Messages

# fmt: off
conversation_id = "conversation_1"  # @param {type:"string"}
# fmt: on

conversation_url = f"{base_url}/{api_version}/projects/{billing_project}/locations/{location}/conversations/{conversation_id}/messages"

conversation_response = requests.get(conversation_url, headers=headers)

# Handle the response
if conversation_response.status_code == 200:
  print("Conversation fetched successfully!")
  print(json.dumps(conversation_response.json(), indent=2))
else:
  print(
      f"Error while fetching conversation: {conversation_response.status_code}"
  )
  print(conversation_response.text)

Conversation fetched successfully!
{
  "messages": [
    {
      "messageId": "307c9695-a69e-4cd4-8b68-c2dbebfa8956",
      "message": {
        "timestamp": "2026-05-26T08:36:22.795003Z",
        "systemMessage": {
          "text": {
            "parts": [
              "What are the top 5 products by total units sold?",
              "Which product brands generate the most revenue?",
              "Predict the revenue for the top-selling product for the next 6 months."
            ],
            "textType": "FOLLOWUP_QUESTIONS"
          }
        }
      }
    },
    {
      "messageId": "35a0d689-8d73-42bb-9f30-367e332322df",
      "message": {
        "timestamp": "2026-05-26T08:36:22.000540Z",
        "systemMessage": {
          "text": {
            "parts": [
              "### Insights\n\n*   **Revenue Leader:** The **Woolrich Arctic Parka DF** is the highest-grossing product, generating **$13,860** in total revenue.\n*   **High-Value Apparel:** Most of the top-performing products are high-value winter wear or sports apparel, such as the **The North Face Freedom Mens Ski Pants** and the **Canada Goose Women's Mystique** parka.\n*   **Revenue Concentration:** These top 5 products alone have generated significant revenue, ranging from approximately $8,100 to nearly $14,000 each."
            ],
            "textType": "FINAL_RESPONSE"
          }
        }
      }
    },
    {
      "messageId": "ded0074e-3203-4f6e-8bf5-f0548029bcc6",
      "message": {
        "timestamp": "2026-05-26T08:36:21.323691Z",
        "systemMessage": {
          "chart": {
            "result": {
              "vegaConfig": {
                "data": {
                  "values": [
                    {
                      "product_name": "Woolrich Arctic Parka DF",
                      "total_revenue": 13860,
                      "product_id": 24110
                    },
                    {
                      "product_id": 23989,
                      "total_revenue": 12642,
                      "product_name": "The North Face Freedom Mens Ski Pants 2013"
                    },
                    {
                      "product_id": 24899,
                      "total_revenue": 9030,
                      "product_name": "Nike Jordan Retro 11 Bred Bootie Socks"
                    },
                    {
                      "product_name": "Canada Goose Women&#39;s Mystique",
                      "product_id": 2557,
                      "total_revenue": 9000
                    },
                    {
                      "product_id": 24201,
                      "total_revenue": 8127,
                      "product_name": "Mens Nike AirJordan Varsity Hoodie Jacket Grey / Black 451582-066"
                    }
                  ]
                },
                "height": 400,
                "title": "Top 5 Products by Total Revenue",
                "encoding": {
                  "x": {
                    "type": "nominal",
                    "sort": "-y",
                    "field": "product_name",
                    "title": "Product Name"
                  },
                  "tooltip": [
                    {
                      "type": "nominal",
                      "field": "product_id",
                      "title": "Product ID"
                    },
                    {
                      "title": "Product Name",
                      "field": "product_name",
                      "type": "nominal"
                    },
                    {
                      "title": "Total Revenue",
                      "type": "quantitative",
                      "format": "$,.2f",
                      "field": "total_revenue"
                    }
                  ],
                  "y": {
                    "field": "total_revenue",
                    "type": "quantitative",
                    "title": "Total Revenue ($)"
                  }
                },
                "mark": "bar",
                "width": 600,
                "$schema": "https://vega.github.io/schema/vega-lite/v4.17.0.json",
                "config": {
                  "view": {
                    "continuousHeight": 300,
                    "continuousWidth": 400
                  }
                },
                "usermeta": {
                  "chart_id": "top_5_products_revenue_bar_chart",
                  "data_result_name": "top_5_products_revenue"
                }
              },
              "image": {}
            }
          }
        }
      }
    },
    {
      "messageId": "e632e1c4-537c-4677-9b8d-2669551c5225",
      "message": {
        "timestamp": "2026-05-26T08:36:20.667467Z",
        "systemMessage": {
          "chart": {
            "query": {
              "dataResultName": "top_5_products_revenue"
            }
          }
        }
      }
    },
    {
      "messageId": "122a6328-85b7-4a7e-8f06-cb091bd23b84",
      "message": {
        "timestamp": "2026-05-26T08:36:19.953531Z",
        "systemMessage": {
          "data": {
            "bigQueryJob": {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "jobId": "job_uFvRzuRlg_vEa2YftjG0b8B1XOsk",
              "destinationTable": {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "_74bc875385d1974b5cb8f6b881e8447ecb3062fa",
                "tableId": "anon925ba124e37fe7989bdf32c2f5c130ee800bd2974440d1006e46845dfc1ad7a1"
              },
              "location": "US",
              "schema": {}
            }
          }
        }
      }
    },
    {
      "messageId": "87d6c03c-d7cc-4871-9522-0086b36e0677",
      "message": {
        "timestamp": "2026-05-26T08:36:19.195419Z",
        "systemMessage": {
          "data": {
            "generatedSql": "SELECT\n    products.id AS product_id,\n    products.name AS product_name,\n    SUM(order_items.sale_price) AS total_revenue\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products\nINNER JOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items\n    ON products.id = order_items.product_id\nGROUP BY\n    product_id,\n    product_name\nORDER BY\n    total_revenue DESC\nLIMIT 5;"
          }
        }
      }
    },
    {
      "messageId": "0f0cbf44-fc3e-49d0-aa69-2a0f975d22da",
      "message": {
        "timestamp": "2026-05-26T08:36:18.451550Z",
        "systemMessage": {
          "data": {
            "query": {
              "datasources": [
                {
                  "bigqueryTableReference": {
                    "projectId": "project-4edfdecd-6192-4f0d-be4",
                    "datasetId": "ecommerce",
                    "tableId": "order_items"
                  }
                },
                {
                  "bigqueryTableReference": {
                    "projectId": "project-4edfdecd-6192-4f0d-be4",
                    "datasetId": "ecommerce",
                    "tableId": "products"
                  }
                }
              ]
            }
          }
        }
      }
    },
    {
      "messageId": "186a90cd-0fa1-460f-baf2-e85c5a907b94",
      "message": {
        "timestamp": "2026-05-26T08:36:17.619573Z",
        "systemMessage": {
          "data": {
            "result": {
              "data": [
                {
                  "product_name": "Woolrich Arctic Parka DF",
                  "total_revenue": 13860,
                  "product_id": 24110
                },
                {
                  "product_id": 23989,
                  "total_revenue": 12642,
                  "product_name": "The North Face Freedom Mens Ski Pants 2013"
                },
                {
                  "product_id": 24899,
                  "total_revenue": 9030,
                  "product_name": "Nike Jordan Retro 11 Bred Bootie Socks"
                },
                {
                  "product_name": "Canada Goose Women's Mystique",
                  "product_id": 2557,
                  "total_revenue": 9000
                },
                {
                  "product_id": 24201,
                  "total_revenue": 8127,
                  "product_name": "Mens Nike AirJordan Varsity Hoodie Jacket Grey / Black 451582-066"
                }
              ],
              "name": "top_5_products_revenue",
              "schema": {
                "fields": [
                  {
                    "name": "product_id",
                    "type": "INTEGER",
                    "mode": "NULLABLE"
                  },
                  {
                    "name": "product_name",
                    "type": "STRING",
                    "mode": "NULLABLE"
                  },
                  {
                    "name": "total_revenue",
                    "type": "FLOAT",
                    "mode": "NULLABLE"
                  }
                ]
              }
            }
          }
        }
      }
    },
    {
      "messageId": "4873923c-7161-44a9-9cf3-0c91bb8219df",
      "message": {
        "timestamp": "2026-05-26T08:36:16.994548Z",
        "systemMessage": {
          "data": {
            "bigQueryJob": {
              "projectId": "project-4edfdecd-6192-4f0d-be4",
              "jobId": "job_uFvRzuRlg_vEa2YftjG0b8B1XOsk",
              "destinationTable": {
                "projectId": "project-4edfdecd-6192-4f0d-be4",
                "datasetId": "_74bc875385d1974b5cb8f6b881e8447ecb3062fa",
                "tableId": "anon925ba124e37fe7989bdf32c2f5c130ee800bd2974440d1006e46845dfc1ad7a1"
              },
              "location": "US",
              "schema": {}
            }
          }
        }
      }
    },
    {
      "messageId": "a1b1b031-1f54-46e4-9d13-b852f07fca9c",
      "message": {
        "timestamp": "2026-05-26T08:36:16.417020Z",
        "systemMessage": {
          "data": {
            "generatedSql": "SELECT\n    products.id AS product_id,\n    products.name AS product_name,\n    SUM(order_items.sale_price) AS total_revenue\nFROM\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.products` AS products\nINNER JOIN\n    `project-4edfdecd-6192-4f0d-be4.ecommerce.order_items` AS order_items\n    ON products.id = order_items.product_id\nGROUP BY\n    product_id,\n    product_name\nORDER BY\n    total_revenue DESC\nLIMIT 5;"
          }
        }
      }
    },
    {
      "messageId": "0e22dd8f-5086-4abd-b83a-d87efef6f03e",
      "message": {
        "timestamp": "2026-05-26T08:36:15.753476Z",
        "systemMessage": {
          "data": {
            "query": {
              "datasources": [
                {
                  "bigqueryTableReference": {
                    "projectId": "project-4edfdecd-6192-4f0d-be4",
                    "datasetId": "ecommerce",
                    "tableId": "order_items"
                  }
                },
                {
                  "bigqueryTableReference": {
                    "projectId": "project-4edfdecd-6192-4f0d-be4",
                    "datasetId": "ecommerce",
                    "tableId": "products"
                  }
                }
              ]
            }
          }
        }
      }
    },
    {
      "messageId": "f33ac3b2-bcaf-4eef-a788-dd4ea8b76514",
      "message": {
        "timestamp": "2026-05-26T08:36:15.044758Z",
        "systemMessage": {
          "text": {
            "parts": [
              "The following data and chart show the top 5 products in terms of total revenue, calculated by summing the sales prices of all items sold for each product."
            ],
            "textType": "FINAL_RESPONSE"
          }
        }
      }
    },
    {
      "messageId": "9cc0b20c-844e-40aa-bc62-e0ad1f04f131",
      "message": {
        "timestamp": "2026-05-26T08:36:14.389839Z",
        "systemMessage": {
          "text": {
            "parts": [
              "My Thought Process for Generating the Final Response",
              "Alright, I've got the data and the visualization components ready. My next step is to construct the complete, polished output for the user. My internal objective is to present a comprehensive answer that not only fulfills the user's request but also offers valuable context and interpretation. Specifically, I recall the user's explicit requirement: a bar graph depicting the top 5 products, meticulously ranked by their total revenue. I have successfully processed the underlying data and now have that result available as `top_5_products_revenue`. Concurrently, I've generated the corresponding visualization, which I've identified with the chart ID `top_5_products_revenue_bar_chart`. My strategy for structuring this final response is deliberate and designed for maximum clarity and utility. I will begin with a concise Your Summary that encapsulates the essence of the findings. This will be followed by the direct presentation of the `top_5_products_revenue` data itself, allowing for granular inspection. Then, I will integrate the `top_5_products_revenue_bar_chart`, providing the visual representation that was requested. Crucially, I will conclude with a section dedicated to Insights, where I'll offer interpretations and highlight the key takeaways derived from both the data and the chart. This structured approach ensures that the user can easily digest the information, understand the underlying numbers, visualize the trends, and gain actionable intelligence."
            ],
            "textType": "THOUGHT"
          }
        }
      }
    },
    {
      "messageId": "258c9511-105f-405b-9d04-40c03c51dc08",
      "message": {
        "timestamp": "2026-05-26T08:36:13.692669Z",
        "systemMessage": {
          "text": {
            "parts": [
              "My Thought Process for Generating the Top 5 Products Revenue Bar Graph",
              "Alright, so the request is clear: I need to visualize the top 5 products based on their total revenue. The output should be a bar graph, and I've already done the heavy lifting by running a SQL query named `top_5_products_revenue`. This query has conveniently provided me with the `product_id`, `product_name`, and `total_revenue` for those top contenders. My next step is to translate this data into a compelling visual. The tool of choice here is Altair, a fantastic Python library for declarative statistical visualization. The user specifically wants the output as a JSON string representing the Vega-Lite specification, which means I'll need to use Python to build this spec and then print it. The requirements are pretty specific: I must import `altair` and `json`. The final output needs to be a JSON string. Crucially, the `alt.Chart()` function needs to reference the `data_result_name`, which is `top_5_products_revenue`. I should use shorthand type annotations for clarity (like `:N` for nominal/categorical and `:Q` for quantitative/numerical). I need to include `usermeta` containing both the `data_result_name` and a `chart_id` (though the `chart_id` wasn't explicitly provided, I'll assume it's something I need to generate or can use a placeholder for). A descriptive title for the chart and clear labels for the axes are essential for interpretability. Now, regarding the chart itself: a bar chart is requested. The instructions mention that horizontal bars are sometimes better for long product names, but the default preference is vertical bars unless specified otherwise. Given this, I'll stick with a vertical bar chart. The x-axis will represent the `product_name`, which is a categorical or nominal variable, hence `:N`. The y-axis will represent `total_revenue`, a quantitative variable, hence `:Q`. So, my plan is quite straightforward: 1. I'll construct the Python code that orchestrates all these requirements. This will involve importing the necessary libraries, creating the Altair chart object, mapping the data columns to the appropriate visual encoding (x and y axes, color, etc.), adding a title, and then serializing the chart specification to a JSON string. 2. Once the code is ready, I'll execute it using the `google:python_interpreter` to ensure it runs correctly and produces the desired JSON output. 3. Finally, I'll present this JSON output as the solution. Essentially, I'm taking the structured data from my SQL query and using Altair's declarative approach to build a visual representation that highlights the revenue performance of the top 5 products. The emphasis is on generating a precise, well-formatted JSON output that conforms to all the specified requirements."
            ],
            "textType": "THOUGHT"
          }
        }
      }
    },
    {
      "messageId": "8275ffc7-3ff8-4863-bf96-641721d07f6f",
      "message": {
        "timestamp": "2026-05-26T08:35:59.301762Z",
        "systemMessage": {
          "text": {
            "parts": [
              "My Thought Process for Generating the Top 5 Products by Revenue Bar Chart",

## Multi-turn Conversation with Data Agent or Inline Context

In [28]:
# @title get_stream function for multi-turn conversation

# NOTE: This methods is same as get_stream() method present in Streaming Chat Messages section.
# The only difference is that - here we are storing the response in an array "conversation_messages" to save the conversation.


def get_stream_multi_turn(url, json, conversation_messages):
  s = requests.Session()

  acc = ""

  with s.post(url, json=json, headers=headers, stream=True) as resp:
    for line in resp.iter_lines():
      if not line:
        continue

      decoded_line = str(line, encoding="utf-8")

      if decoded_line == "[{":
        acc = "{"
      elif decoded_line == "}]":
        acc += "}"
      elif decoded_line == ",":
        continue
      else:
        acc += decoded_line

      if not is_json(acc):
        continue

      data_json = json_lib.loads(acc)
      # Store the response to be used in next iteration.
      conversation_messages.append(data_json)

      if "systemMessage" not in data_json:
        if "error" in data_json:
          handle_error(data_json["error"])
        continue

      if "text" in data_json["systemMessage"]:
        handle_text_response(data_json["systemMessage"]["text"])
      elif "schema" in data_json["systemMessage"]:
        handle_schema_response(data_json["systemMessage"]["schema"])
      elif "data" in data_json["systemMessage"]:
        handle_data_response(data_json["systemMessage"]["data"])
      elif "chart" in data_json["systemMessage"]:
        handle_chart_response(data_json["systemMessage"]["chart"])
      else:
        colored_json = highlight(
            acc, lexers.JsonLexer(), formatters.TerminalFormatter()
        )
        print(colored_json)
      print("\n")
      acc = ""

In [ ]:
# @title Multi-turn Conversation helper function
chat_url = (
    f"{base_url}/{api_version}/projects/{billing_project}/locations/global:chat"
)

# Re-used across requests to track previous turns
conversation_messages = []

# fmt: off
context = "data_agent_context" # @param ["data_agent_context", "inline_context"]
# Only for data_agent_context
data_agent_id = "data_agent_1"  # @param {type:"string"}
# fmt: on


# Helper function for calling the API
def multi_turn_conversation(msg):
  userMessage = {"userMessage": {"text": msg}}

  # Send multi-turn request by including previous turns, plus new message
  conversation_messages.append(userMessage)

  datasource_refs = dict(datasource_references)

  # Construct the payload
  chat_payload = (
      {
          "parent": f"projects/{billing_project}/locations/global",
          "messages": conversation_messages,
          "data_agent_context": {
              "data_agent": (
                  f"projects/{billing_project}/locations/{location}/dataAgents/{data_agent_id}"
              ),
          },
      }
      if context == "data_agent_context"
      else {
          "parent": f"projects/{billing_project}/locations/global",
          "messages": conversation_messages,
          "inline_context": {
              "datasource_references": datasource_refs,
          },
      }
  )

  if looker_selected:
    if context == "inline_context":
      datasource_refs["looker"] = {
          **datasource_refs["looker"],
          "credentials": looker_credentials,
      }
      if use_looker_golden_queries:
        chat_payload["inline_context"][
            "looker_golden_queries"
        ] = looker_golden_queries
    else:
      chat_payload["data_agent_context"]["credentials"] = looker_credentials
  elif bq_selected and context == "inline_context":
    if use_example_queries:
      chat_payload["inline_context"]["example_queries"] = example_queries
    if use_glossary_terms:
      chat_payload["inline_context"]["glossary_terms"] = glossary_terms

  # Call get_stream_multi_turn method to stream the response
  get_stream_multi_turn(chat_url, chat_payload, conversation_messages)

In [ ]:
# Send first-turn request
multi_turn_conversation(
    "List of the top 5 states by the total number of airports"
)

In [ ]:
# Send follow-up-turn request
multi_turn_conversation("Can you please make it a pie chart?")